---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-headless
  namespace: services
spec:
  selector:
    matchLabels:
      app: service-headless
  template:
    metadata:
      labels:
        app: service-headless
    spec:
      containers:
        - name: service-headless
          image: gitlab.xxx.xx:5050/service-headless-browser/service-headless-browser:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          