---
apiVersion: v1
kind: Service
metadata:
  name: service-headless
  namespace: services
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: service-headless
  ports:
    - port: 8080
      targetPort: 8080