---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fonts-data
provisioner: storage.io/nfs 
parameters:
  archiveOnDelete: "false"
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fonts-pvc
  namespace: mw-services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fonts-data
  resources:
    requests:
      storage: 1Gi
