apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services

resources:
  - ../../../mw-headless-browser
  - keda-scaler.yml
  - http_route.yml
  - default-headers.yml 

patches:
  - path: patch-deployment.yml
